version: '3'

services:
  db:
    image: postgres
    volumes:
    - ./tmp/teampact-db:/var/lib/postgresql/data

  app:
    build: .
    image: teampact/teampact
    command: foreman start
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 3200:3200
      - 3040:3040
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:@db:5432/teampact_development
      RAILS_LOG_TO_STDOUT: "true"

volumes:
  node_modules:
