version: '3'

services:
  db:
    image: postgres
    volumes:
    - ./tmp/teampact-db:/var/lib/postgresql/data

  app:
    build: .
    image: teampact/teampact
    command: bundle exec rails s -b 0.0.0.0 -p 3200
    volumes:
    - .:/app
    - node_modules:/app/node_modules
    ports:
    - 3200:3200
    depends_on:
    - db
    environment:
      DATABASE_URL: postgres://postgres:@db:5432/teampact_development
      RAILS_LOG_TO_STDOUT: "true"

  webpacker:
    image: teampact/teampact
    command: ./bin/webpack-dev-server
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    volumes:
    - .:/app
    - node_modules:/app/node_modules
    ports:
    - 3040:3040

volumes:
  node_modules:
