default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: teampact_development

test:
  <<: *default
  database: teampact_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
